// AUTO-GENERATED by scripts/pin-asr-artifacts.js — do not edit by hand.
// Sherpa-ONNX ASR archives pinned by size + SHA-256 (GitHub Release only).

export interface AsrFilePin {
  name: string;
  bytes: number;
  sha256: string;
}

export interface AsrPackPin {
  id: 'builtin' | 'upgrade';
  title: string;
  archiveUrl: string;
  archiveBytes: number;
  archiveSha256: string;
  files: AsrFilePin[];
}

export const ASR_PINS: {builtin: AsrPackPin; upgrade: AsrPackPin} = {
  "builtin": {
    "id": "builtin",
    "title": "Zipformer 14M zh (streaming)",
    "archiveUrl": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23.tar.bz2",
    "archiveBytes": 74004050,
    "archiveSha256": "2cbd71b640d9c37d3784f29367333a4577b0398b62e9deeed418170b081cba8b",
    "files": [
      {
        "name": "decoder-epoch-99-avg-1.int8.onnx",
        "bytes": 1888682,
        "sha256": "22f123bb8cba9b38974b3df18a3f45e7081f4985ebb2e075d9f21f618c468bbf"
      },
      {
        "name": "decoder-epoch-99-avg-1.onnx",
        "bytes": 7509745,
        "sha256": "5ee0f03a2768ff1d5c83ef3a493243c7935d316cd41280037b14783a3467cc78"
      },
      {
        "name": "encoder-epoch-99-avg-1.int8.onnx",
        "bytes": 21621684,
        "sha256": "1c556ea57cec304e55ec4b72e52c1cc098bb01476ed7d90f3de939fe126487b1"
      },
      {
        "name": "encoder-epoch-99-avg-1.onnx",
        "bytes": 40948171,
        "sha256": "84c6a8f372686faa5b8f45f2d79f0816f76dcd9f547acb9a90eba2772d7eda8b"
      },
      {
        "name": "joiner-epoch-99-avg-1.int8.onnx",
        "bytes": 1795562,
        "sha256": "a7cf9d82757bdcf786059454495a9ca95e4bd7347f72473fc08d794475c36169"
      },
      {
        "name": "joiner-epoch-99-avg-1.onnx",
        "bytes": 7109975,
        "sha256": "030212efaea9a8b6a4fa98faf6ac6055529c4408cf4865e898220ddd02780f34"
      },
      {
        "name": "tokens.txt",
        "bytes": 48697,
        "sha256": "8b294db9045d6e5f94647f4c1eec1af4da143a75053c399611444b378ff966ac"
      }
    ]
  },
  "upgrade": {
    "id": "upgrade",
    "title": "SenseVoice zh/en/ja/ko/yue (offline)",
    "archiveUrl": "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2",
    "archiveBytes": 1047870769,
    "archiveSha256": "f6b2a72ebcb1ac7a764d4cfccd886e6bcb2a95c4657c2199d0ba95ed4b9ea71a",
    "files": [
      {
        "name": "model.int8.onnx",
        "bytes": 239233841,
        "sha256": "c71f0ce00bec95b07744e116345e33d8cbbe08cef896382cf907bf4b51a2cd51"
      },
      {
        "name": "model.onnx",
        "bytes": 937617178,
        "sha256": "977016bd9c79f9eb343430b5cc305e07ab64d5212dff41b0dcfa1694bee9a8cb"
      },
      {
        "name": "tokens.txt",
        "bytes": 315894,
        "sha256": "f449eb28dc567533d7fa59be34e2abca8784f771850c78a47fb731a31429a1dc"
      }
    ]
  }
} as const;
